In [29]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.0f}'.format # display numbers as integers

In [83]:
data = pd.read_csv('Data_Regional_Exports_Imports_20200415.csv', skiprows=2,
                  usecols=[0,3,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26],
                  nrows=45, index_col=1)

In [84]:
relevant_data = data[(data.Include=='Yes')]

In [86]:
entering = relevant_data.groupby('Hydrologic Region').sum()

In [87]:
entering

,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Hydrologic Region,,,,,,,,,,,,,,,,,,
Central Coast Region,105,164,140,175,183,166,198,138,119,201,142,133,117,111,186,162,110,66
Colorado River Region,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
San Francisco Bay Region,471,777,629,628,828,813,853,744,758,985,889,842,731,545,751,779,621,571
San Joaquin River Region,5119,5346,6174,4572,6527,7460,7216,6149,6461,5686,3171,3880,6601,6340,4401,3663,2009,1850
South Coast Region,844,738,1401,983,1537,1772,1837,1328,1499,1723,1036,1014,1295,1450,1359,1057,430,691
South Lahontan Region,729,795,1509,1065,1613,1864,1927,1575,1831,2021,1193,1185,1480,1678,1568,1211,544,759
Tulare Lake Region,2952,3666,4414,2961,3479,4169,4034,4447,4644,3820,2118,1859,3189,4695,3766,2402,893,1093

In [89]:
leaving = relevant_data.groupby('Leaving').sum()

In [90]:
leaving

,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Leaving,,,,,,,,,,,,,,,,,,
Central Coast Region,66,118,89,133,127,110,135,88,64,145,98,103,82,67,141,121,82,45
Sacramento River Region,5188,5579,6246,4652,6777,7682,7478,6375,6671,5953,3448,4124,6820,6558,4631,3929,2238,2072
San Francisco Bay Region,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
San Joaquin River Region,3371,4232,4995,3528,4081,4784,4654,4987,5219,4562,2752,2468,3714,5041,4308,2934,1293,1448
South Coast Region,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
South Lahontan Region,844,738,1401,983,1537,1772,1837,1328,1499,1723,1036,1014,1295,1450,1359,1057,430,691
Tulare Lake Region,751,819,1536,1088,1645,1896,1961,1603,1859,2053,1215,1204,1502,1703,1592,1233,564,774

In [91]:
balance = entering-leaving
balance = balance.round(decimals=0)
balance = balance.drop(['Sacramento River Region'])

In [92]:
balance = balance.assign(mean=balance.mean(axis=1))

In [93]:
balance

,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,mean
Central Coast Region,39,46,51,42,56,56,63,50,55,56,44,30,35,44,45,41,28,21,45
Colorado River Region,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
San Francisco Bay Region,471,777,629,628,828,813,853,744,758,985,889,842,731,545,751,779,621,571,734
San Joaquin River Region,1748,1114,1179,1044,2446,2676,2562,1162,1242,1124,419,1412,2887,1299,93,729,716,402,1347
South Coast Region,844,738,1401,983,1537,1772,1837,1328,1499,1723,1036,1014,1295,1450,1359,1057,430,691,1222
South Lahontan Region,-115,57,108,82,76,92,90,247,332,298,157,171,185,228,209,154,114,68,142
Tulare Lake Region,2201,2847,2878,1873,1834,2273,2073,2844,2785,1767,903,655,1687,2992,2174,1169,329,319,1867

In [97]:
balance_2005_2015 = balance.iloc[:, [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]]

In [98]:
balance_2005_2015 = balance_2005_2015.assign(mean=balance_2005_2015.mean(axis=1))

In [99]:
balance_2005_2015

,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,mean
Central Coast Region,50,55,56,44,30,35,44,45,41,28,21,41
Colorado River Region,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan
San Francisco Bay Region,744,758,985,889,842,731,545,751,779,621,571,747
San Joaquin River Region,1162,1242,1124,419,1412,2887,1299,93,729,716,402,1044
South Coast Region,1328,1499,1723,1036,1014,1295,1450,1359,1057,430,691,1171
South Lahontan Region,247,332,298,157,171,185,228,209,154,114,68,197
Tulare Lake Region,2844,2785,1767,903,655,1687,2992,2174,1169,329,319,1602

In [105]:
with pd.ExcelWriter('D:/Telework/CA Water Plan/Code/Sac_Delta_Supplies_Deliveries.xlsx') as writer:
    balance.to_excel(writer, sheet_name='All Years')
    balance_2005_2015.to_excel(writer, sheet_name='2005_2015')